### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by DCastile** [kz26/PyExcelerate#50]
def get_col_xml_string(self, col):
		if col in self._col_styles and not self._col_styles[col].is_default:
			style = self._col_styles[col]
			if style.size == -1:
				size = 0
				for x, row in self._cells.items():
					if col in row:
						# size = max((len(str(row[col])) * 7 + 5) / 7, size)
                        size = max((len(str(row[col])) * 7 + 5) / 7, size)

**Comment by kevmo314** [comment]
Could you clarify the issue you're seeing? I'm not sure what I'm supposed to be looking at in that code snippet.

**Comment by DCastile** [comment]
col = u'Kommunales Gebietsrechenzentrum Hessen Körperschaft des öffentlichen Rechts'

Traceback (most recent call last):
  File "C:/Renewal-Generator/main.py", line 85, in <module>
    wb.save(FILE_PATH)
  File "C:\Miniconda\lib\site-packages\pyexcelerate\Workbook.py", line 81, in save
    self._save(open(filename, 'wb'))
  File "C:\Miniconda\lib\site-packages\pyexcelerate\Workbook.py", line 78, in _save
    self._writer.save(file_handle)
  File "C:\Miniconda\lib\site-packages\pyexcelerate\Writer.py", line 58, in save
    for s in sheetStream:
  File "C:\Miniconda\lib\site-packages\jinja2\environment.py", line 1013, in generate
Flagged Lines:  1
    yield self.environment.handle_exception(exc_info, True)
  File "C:\Miniconda\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Miniconda\lib\site-packages\pyexcelerate\templates\xl\worksheets\sheet.xml", line 10, in top-level template code
    {% if worksheet.col_styles %}<cols>{% for x, column in worksheet.col_styles %}{{ worksheet.get_col_xml_string(x) }}</col>{% endfor %}</cols>{% endif %}
  File "C:\Miniconda\lib\site-packages\pyexcelerate\Worksheet.py", line 197, in get_col_xml_string
    size = max((len(str(row[col])) * 7 + 5) / 7, size)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 49: ordinal not in range(128)

**Comment by kz26** [comment]
Are you using Python 2.x?

**Comment by DCastile** [comment]
2.7.11

**Comment by kz26** [comment]
OK, thanks. If all goes well I hope to push a new version with this and other fixes this weekend.

**Comment by DCastile** [comment]
size = max((len( '%s' % row[col]) * 7 + 5) / 7, size)

My bad my first post was supposed to include this.. as it seems to work..

**Comment by kz26** [comment]
Version 0.7.0 is live which should fix Unicode issues with styling.
