### ISSUE TITLE
Missing setup.py dependency

### ISSUE THREAD

**Issue by bjones1** [kz26/PyExcelerate#53]
You list `Jinja2` in your `setup.py` as an `install_requires`, but note that it's required at at setup time also (see the trace below). Would you add it to [setup_requires](https://setuptools.readthedocs.io/en/latest/setuptools.html#new-and-changed-setup-keywords) as well?

Thanks!

```
Collecting pyexcelerate (from -r tests\requirements-libraries.txt (line 36))
  Downloading PyExcelerate-0.7.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\appveyor\AppData\Local\Temp\1\pip-build-qis5qcff\pyexcelerate\setup.py", line 4, in <module>
        from pyexcelerate.version import __version__
      File "C:\Users\appveyor\AppData\Local\Temp\1\pip-build-qis5qcff\pyexcelerate\pyexcelerate\__init__.py", line 1, in <module>
        from .Workbook import Workbook
      File "C:\Users\appveyor\AppData\Local\Temp\1\pip-build-qis5qcff\pyexcelerate\pyexcelerate\Workbook.py", line 2, in <module>
        from .Writer import Writer
      File "C:\Users\appveyor\AppData\Local\Temp\1\pip-build-qis5qcff\pyexcelerate\pyexcelerate\Writer.py", line 7, in <module>
        from jinja2 import Environment, FileSystemLoader
    ImportError: No module named 'jinja2'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\appveyor\AppData\Local\Temp\1\pip-build-qis5qcff\pyexcelerate\
Command exited with code 1
```

**Comment by kz26** [comment]
This should have been fixed in version 0.7.1 (it looks like you're using 0.7.0). Could you update and let me know if the issue still exists? Thank you.

**Comment by bjones1** [comment]
Thanks! Will do.

**Comment by bjones1** [comment]
Looks good! Thanks.
